### ISSUE TITLE
E/linker: /data/app/com.ozj.baby-1/lib/arm/libhyphenate_av.so: has text relocations  运行于6.0设备上报错了。望解决下！

### ISSUE THREAD

**Issue by lnfg** [rogerou/Baby#27]
03-28 13:29:03.120 23141-23141/com.ozj.baby E/linker: /data/app/com.ozj.baby-1/lib/arm/libhyphenate_av.so: has text relocations
03-28 13:29:03.127 23141-23141/com.ozj.baby E/AVUncaughtExceptionHandler: AVUncaughtExceptionHandler caught a UnsatisfiedLinkError exception 
03-28 13:29:03.214 23141-23141/com.ozj.baby E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.ozj.baby-1/lib/arm/libhyphenate_av.so: has text relocations
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
                                                                          at com.hyphenate.chat.EMClient.getInstance(Unknown Source)
                                                                          at com.hyphenate.easeui.controller.EaseUI.init(EaseUI.java:124)
                                                                          at com.ozj.baby.EaseUIHelper.init(EaseUIHelper.java:44)
                                                                          at com.ozj.baby.BabyApplicationLike.onCreate(BabyApplicationLike.java:74)
                                                                          at com.tencent.tinker.loader.app.TinkerApplication.onCreate(SourceFile:173)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751)
                                                                          at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rogerou** [comment]
@lnfg 你的是什么CPU类型 可能是So文件不兼容了吧  这个是环信的SO

**Comment by rogerou** [comment]
@lnfg http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations
把TargerVersion调低点，应该是6.0的安全权限提高了导致的
