### ISSUE TITLE
libsqlite.so找不到

### ISSUE THREAD

**Issue by Goach** [rogerou/Baby#28]
catch exception when loading tinker:java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlite.so" not found
                                                               at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                               at java.lang.System.loadLibrary(System.java:1530)
                                                               at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source)
                                                               at com.hyphenate.chat.EMClient.getInstance(Unknown Source)
                                                               at com.hyphenate.easeui.controller.EaseUI.init(EaseUI.java:124)
                                                               at com.ozj.baby.EaseUIHelper.init(EaseUIHelper.java:44)

**Comment by rogerou** [comment]
@Goach 如果用不上Tinker可以先去掉

**Comment by rogerou** [comment]
仔细看了下不是tinker的问题 应该是你把编译包弄到了7.0以上  可以先把targetsdk 弄回23以下 否则应该 自己提供libsqlite的so@Goach
