### ISSUE TITLE
编译通过，但是有500多个错误

### ISSUE THREAD

**Issue by qiuqiu3** [rogerou/Baby#4]
![2016-05-12 10 46 24](https://cloud.githubusercontent.com/assets/10347051/15203107/f6a3b74e-1832-11e6-9390-f64766e7058d.png)

**Comment by rogerou** [comment]
@qiuqiu3 这个是因为用了Leakcanary就这样了，而且在6.0版本Debug时候还会经常Dumping Memory，这个和Leakcanary有点关系，可能是因为兼容的问题吧。上边还有些是百度地图SDK报错的，我上StackOverFLow查了几次都没有找到特别好的答复，但是又不影响的整体的运行，我就暂时没管了。我待会吃完午饭去详细查看有解决办法再通知你。

**Comment by rogerou** [comment]
@qiuqiu3  对了，之前有试过混淆时才会出现这样的问题，我等等把混淆的Proguard改改，你再Update试试。

**Comment by rogerou** [comment]
@qiuqiu3 其实我混淆已经把这些第三方库混淆了，但是它还是会提示，而且在DEBUG下也会出现，但是的确不影响使用，然后我看到了这个：
http://stackoverflow.com/questions/3308010/what-is-the-ignoring-innerclasses-attribute-warning-output-during-compilation/3308059#3308059
大概意思就是说这种警告在使用Jar包的时候是十分普遍的，但是又不是十分要紧的事情，不影响使用可以不理睬。。。好吧，其实我不是我不想修改。。。

**Comment by qiuqiu3** [comment]
@rogerou 谢谢回复。不比真机运行后又报错了。
`
                                                            java.lang.NoClassDefFoundError: rx.subjects.SerializedSubject
                                                                at com.ozj.baby.mvp.model.rx.RxBus.<init>(RxBus.java:18)
                                                                at com.ozj.baby.di.module.ApplicationModule.<init>(ApplicationModule.java:33)
                                                                at com.ozj.baby.BabyApplication.initComponet(BabyApplication.java:56)
                                                                at com.ozj.baby.BabyApplication.initThirdService(BabyApplication.java:43)
                                                                at com.ozj.baby.BabyApplication.onCreate(BabyApplication.java:33)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4438)
                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
                                                                at dalvik.system.NativeStart.main(Native Method)
`

**Comment by huronghui** [comment]
@qiuqiu3 @rogerou  换了真机还是有500多错误。。求解/(ㄒoㄒ)/~~

**Comment by qiuqiu3** [comment]
@huronghui 我的真机会报NoClassDefFoundError错误，然后闪退，你的没问题？

**Comment by rogerou** [comment]
http://stackoverflow.com/questions/3308010/what-is-the-ignoring-innerclasses-attribute-warning-output-during-compilation/3308059#3308059
@huronghui  你可以把leackcanary的依赖去掉，要不是用地图也可以 把地图的Sdk去掉就可以了。

**Comment by rogerou** [comment]
@qiuqiu3 rebulid一下

**Comment by qiuqiu3** [comment]
@rogerou 我把 build 目录删除再运行就好了，但是又来了一个问题。
换了 idk 1.7 和 1.8 总是依旧。

![2016-05-12 2 05 38](https://cloud.githubusercontent.com/assets/10347051/15205528/affc2a48-184a-11e6-822c-74ae151611ce.png)

**Comment by qiuqiu3** [comment]
@rogerou 我把百度地图的so文件还有jar包删除了，又删除了 easeui 里面map相关的activity，现在可以成功运行了。谢谢

**Comment by rogerou** [comment]
@qiuqiu3 
congratulation  , 愉快地观摩吧  : )

**Comment by huronghui** [comment]
@rogerou 
我报的是你一开始报的错误，去除了leackcanary的依赖还是会报这错误

**Comment by rogerou** [comment]
@huronghui  是一开始的那些警告？如果是的话你可以跟他一样把百度地图的相关包删了，当然调用到的第地方也要删除掉

**Comment by huronghui** [comment]
@rogerou  可以了，去除了 jniLibs 中的百度so 架包，并且rebuild了一下，已经可以运行了，这几天麻烦您了~万分感谢。。

**Comment by rogerou** [comment]
@huronghui  不谢哈，主要你要把用到百度地图的地方也要删除掉哦。不然会崩溃

**Comment by qiuqiu3** [comment]
@rogerou 这个问题可以 close 了。
